theme: jekyll-theme-cayman

title: Blog!
description: ...
baseurl: /blog
url: https://chiyuukei.github.io

show_downloads: false
darkmode: false
logo_url: https://chiyuukei.github.io/tools/icon/icon.jpg
