title: お客様、ようこそ！
description: ここは、私がゴミ捨て場を手を入れて遊び場にした場所です。会えてうれしいよ (,,>﹏<,,)
show_downloads: false
hide_github: true

collections:
  blog:
    output: true
    permalink: /blog/:title/

buttons:
  - text: ""
    href: "https://github.com/chiyuukei/blog/"

remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: https://chiyuukei.github.io
